version: '3'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - orm_data_mysql_hitrix:/var/lib/mysql
    ports:
      - "9004:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hitrix
      - MYSQL_PASSWORD=root

  redis:
    image: redis/redis-stack
    volumes:
      - orm_data_redis_hitrix:/data
    ports:
      - "9002:6379"
      - "8001:8001"

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8002:8001"
    volumes:
      - redisinsight_hitrix:/var/lib/redisinsight

  services:
    build:
      context: ""
      dockerfile: services/Dockerfile
    depends_on:
      - mysql
      - redis
    ports:
      - "9999:9999"
    volumes:
      - ../..:/go/src/github.com/coretrix/hitrix

volumes:
  orm_data_mysql_hitrix:
  orm_data_redis_hitrix:
  redisinsight_hitrix:
